.docs_pages_template:
  stage: deploy
  image: python:3.11-bookworm
  script:
    - apt-get update
    - apt-get install -y git
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/lcbio1/CABSflex_standalone.wiki.git" /tmp/CABSflex_standalone.wiki
    - pip install markdown
    - CABSFLEX_WIKI_ROOT=/tmp/CABSflex_standalone.wiki python scripts/build_html_wiki.py
    - mkdir -p public
    - cp -r docs/* public/
  artifacts:
    paths:
      - public

pages:
  extends: .docs_pages_template
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - .gitlab-ci.yml
        - scripts/build_html_wiki.py
        - docs/assets/**/*
        - docs/README.md
      when: on_success
    - when: never

pages_manual:
  extends: .docs_pages_template
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - when: never
